# Setup
title:               CATRIN
tagline:             'Controllable, Accountable, Transparent: the Responsible Internet'
description:         'This website serves as the face of NWO funded CATRIN project.'
url:                 https://abhishta91.github.io/CATRIN
baseurl:             ''
#paginate:           5
permalink:           pretty

# About/contact
author:
  name:              Catrin
  #url:
  #email:

# Gems
#plugins:
#  - jekyll-paginate

# Custom vars
#version:             1.1.0
#google_analytics_id: #UA-XXXX-Y
